name: Auto-Tweet with GPT-4o & U.S. AI Trends

# on:
#   schedule:
#     - cron: '0 12 * * 1,3,5,6' # Runs at 12 PM UTC on Monday, Wednesday, Friday, Saturday

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install openai tweepy python-dotenv requests

    - name: Run Auto-Tweet Script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      run: python scripts/auto_tweet.py
